//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTELMANAGEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPermission
    {
        public int AccPerID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> Permission { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ModuleList ModuleList { get; set; }
    }
}
