//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTELMANAGEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceHistory
    {
        public int HistoryID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateMaintenance { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public Nullable<decimal> MaintenancePrices { get; set; }
        public int EquipmentID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
