//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTELMANAGEWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RoomType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomType()
        {
            this.Bookings = new HashSet<Booking>();
            this.Rooms = new HashSet<Room>();
        }
    
        public int RoomTypeID { get; set; }
        [Display(Name = "Tên loại phòng")]
        public string RoomTypeName { get; set; }
        [Display(Name = "Giá")]
        public Nullable<decimal> RoomTypePrices { get; set; }
        [Display(Name = "Mô tả")]
        public string RoomTypeDescription { get; set; }
        [Display(Name = "Trạng thái")]
        public byte Disabled { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<int> ModifyUserID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
        [Display(Name = "Trả trước")]
        public Nullable<byte> IsPay { get; set; }
        [Display(Name = "HIển thị trang chủ")]
        public Nullable<byte> IsShowHomePage { get; set; }
        [Display(Name = "Hiển thị")]
        public Nullable<byte> IsShow { get; set; }
        public string RoomTypeImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
